In [1]:
import numpy as np

# Full Singular Value Decomposition(SVD)

In [2]:
arr = np.array([
    [0,0,0,1,0,1,1,0,0],
    [0,0,0,1,1,0,1,0,0],
    [0,1,1,0,2,0,0,0,0],
    [1,0,0,0,0,0,0,1,1]])

print(arr.shape)

(4, 9)


In [3]:
# U=4x4, d=4x9, Vt=9x9
U, d, Vt = np.linalg.svd(arr, full_matrices=True) 

print(U.shape)
print(d.shape)
print(Vt.shape)

(4, 4)
(4,)
(9, 9)


In [4]:
print(d) # [a,b,c,d]

_d = np.zeros((4,9))
_d[:4,:4] = np.diag(d)
print(_d)

d = _d

[2.68731789 2.04508425 1.73205081 0.77197992]
[[2.68731789 0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         2.04508425 0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         1.73205081 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.77197992 0.         0.
  0.         0.         0.        ]]


In [11]:
print(U)
print(d)
print(Vt)

print(U.shape, d.shape, Vt.shape)

[[-2.39751712e-01  7.51083898e-01  9.90665210e-17 -6.15135834e-01]
 [-5.06077194e-01  4.44029376e-01 -1.48599782e-16  7.39407727e-01]
 [-8.28495619e-01 -4.88580485e-01 -4.39152715e-17 -2.73649629e-01]
 [-8.78352025e-17 -2.98807451e-17  1.00000000e+00  1.58797796e-16]]
[[2.68731789 0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         2.04508425 0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         1.73205081 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.77197992 0.         0.
  0.         0.         0.        ]]
[[-1.26987588e-16 -3.08298331e-01 -3.08298331e-01 -2.77536539e-01
  -8.04917216e-01 -8.92159849e-02 -2.77536539e-01 -5.17165587e-17
  -5.17165587e-17]
 [ 2.33985050e-17 -2.38904821e-01 -2.38904821e-01  5.84383395e-01
  -2.60689306e-01  3.67263060e-01  5.84383395e-01 -4.00759068e-17
  -4.00759068e-17]
 [ 5.77350269e-01 -3.27798955e-17  4.4540499

In [20]:
_arr = U@(d@Vt)
print(_arr.round(2))

print(np.allclose(arr, _arr)) # see if two arrays are equal.

[[ 0. -0. -0.  1. -0.  1.  1.  0.  0.]
 [ 0.  0.  0.  1.  1. -0.  1. -0. -0.]
 [ 0.  1.  1. -0.  2. -0. -0.  0.  0.]
 [ 1. -0.  0.  0. -0.  0. -0.  1.  1.]]
True


### np.allclose
 - returns True if two arrays are element-wise equal within a tolerance.

### np.dot
 - dot product of two arrays.
 - if both `a` and `b` are 1-D arrays, it is inner product of vectors(without complex conjugation).
 - if both `a` and `b` are 2-D arrays, it is matrix multiplication, but using :func:`matmul` or ``a @ b`` is preferred.

# Truncated Singular Value Decomposition(Truncated SVD)

In [8]:
t=2 # truncate to 2 units = # of topics

In [14]:
U_t = U[:,:t] # 4*4 -> 4*2
print(U_t.shape)

d_t = d[:t,:t] # 4*9 -> 2*2
print(d_t.shape)

Vt_t = Vt[:t,:] # 9*9 -> 2*9
print(Vt_t.shape)

(4, 2)
(2, 2)
(2, 9)


In [17]:
_U_t = U_t@(d_t@Vt_t)
print(_U_t.round(2))

print(_U_t.shape)

[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.    0.    0.    0.  ]]
(4, 9)
