In [2]:
import transformers
from transformers import AutoTokenizer, TFBertForMaskedLM, FillMaskPipeline

In [4]:
# import Bert tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = TFBertForMaskedLM.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [7]:
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')

print(inputs.input_ids)# numeric encoding of tokenized text
print(inputs.token_type_ids)# binary mask identifying different sequences in the model
print(inputs.attention_mask)# binary mask identifying the padded elements in the input

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)
tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)
tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [8]:
pipe = FillMaskPipeline(model, tokenizer)

print(pipe('Soccer is a really fun [MASK].'))

[{'score': 0.7672244906425476, 'token': 4368, 'token_str': 'sport', 'sequence': 'soccer is a really fun sport.'}, {'score': 0.16400133073329926, 'token': 2208, 'token_str': 'game', 'sequence': 'soccer is a really fun game.'}, {'score': 0.015704695135354996, 'token': 2518, 'token_str': 'thing', 'sequence': 'soccer is a really fun thing.'}, {'score': 0.007100079674273729, 'token': 2154, 'token_str': 'day', 'sequence': 'soccer is a really fun day.'}, {'score': 0.0061269705183804035, 'token': 4023, 'token_str': 'activity', 'sequence': 'soccer is a really fun activity.'}]


In [9]:
print(pipe('I went to [MASK] this morning.'))

[{'score': 0.3044912815093994, 'token': 2147, 'token_str': 'work', 'sequence': 'i went to work this morning.'}, {'score': 0.2570076584815979, 'token': 2793, 'token_str': 'bed', 'sequence': 'i went to bed this morning.'}, {'score': 0.08158309012651443, 'token': 2082, 'token_str': 'school', 'sequence': 'i went to school this morning.'}, {'score': 0.07317700237035751, 'token': 3637, 'token_str': 'sleep', 'sequence': 'i went to sleep this morning.'}, {'score': 0.06206969916820526, 'token': 2465, 'token_str': 'class', 'sequence': 'i went to class this morning.'}]


# Klue/BERT-base for Korean

In [11]:
tokenizer_k = AutoTokenizer.from_pretrained("klue/bert-base")
model_k = TFBertForMaskedLM.from_pretrained("klue/bert-base")

tokenizer_config.json:   0%|          | 0.00/289 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/425 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/248k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/495k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/445M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForMaskedLM: ['bert.embeddings.position_ids']
- This IS expected if you are initializing TFBertForMaskedLM from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForMaskedLM from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [13]:
inputs_k = tokenizer_k('축구는 정말 재밌는 [MASK]입니다.', return_tensors='tf')

print(inputs_k.input_ids)# numeric encoding of tokenized text
print(inputs_k.token_type_ids)# binary mask identifying different sequences in the model
print(inputs_k.attention_mask)# binary mask identifying the padded elements in the input

tf.Tensor([[   2 4713 2259 3944 7478 2259    4 3714   18    3]], shape=(1, 10), dtype=int32)
tf.Tensor([[0 0 0 0 0 0 0 0 0 0]], shape=(1, 10), dtype=int32)
tf.Tensor([[1 1 1 1 1 1 1 1 1 1]], shape=(1, 10), dtype=int32)


In [15]:
pipe_k = FillMaskPipeline(model_k, tokenizer_k)

print(pipe_k('축구는 정말 재밌는 [MASK]입니다.'))

[{'score': 0.7974652051925659, 'token': 4559, 'token_str': '스포츠', 'sequence': '축구는 정말 재밌는 스포츠 입니다.'}, {'score': 0.05449341982603073, 'token': 4171, 'token_str': '게임', 'sequence': '축구는 정말 재밌는 게임 입니다.'}, {'score': 0.04056255519390106, 'token': 5260, 'token_str': '종목', 'sequence': '축구는 정말 재밌는 종목 입니다.'}, {'score': 0.01781545951962471, 'token': 3682, 'token_str': '경기', 'sequence': '축구는 정말 재밌는 경기 입니다.'}, {'score': 0.013921468518674374, 'token': 575, 'token_str': '것', 'sequence': '축구는 정말 재밌는 것 입니다.'}]


In [16]:
print(pipe_k('오늘 아침에 [MASK]에 갔습니다.'))

[{'score': 0.023367268964648247, 'token': 3671, 'token_str': '서울', 'sequence': '오늘 아침에 서울 에 갔습니다.'}, {'score': 0.014852304011583328, 'token': 3693, 'token_str': '중국', 'sequence': '오늘 아침에 중국 에 갔습니다.'}, {'score': 0.014125668443739414, 'token': 3902, 'token_str': '부산', 'sequence': '오늘 아침에 부산 에 갔습니다.'}, {'score': 0.01313132792711258, 'token': 3900, 'token_str': '대구', 'sequence': '오늘 아침에 대구 에 갔습니다.'}, {'score': 0.012712078168988228, 'token': 3708, 'token_str': '일본', 'sequence': '오늘 아침에 일본 에 갔습니다.'}]
